name: Formatting check

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install clang-format -y

    - name: Check formatting
      run: |
        files=$(find . -name '*.cpp' -o -name '*.h')
        for file in $files; do
          clang-format -n -Werror $file
        done
